services:
  - type: web
    name: corre_map_test
    env: python
    plan: free
    buildCommand: "go build -tags netgo -ldflags '-s -w' -o app"
    startCommand: "gunicorn correlation_project.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: "correlation_project.settings"
